"""step7 delivery zones slots holds cart ship

Revision ID: 062ca15d6b09
Revises: b2e3c3000095
Create Date: 2026-09-07 16:07:11.540599
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '062ca15d6b09'
down_revision: Union[str, None] = 'b2e3c3000095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_slots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=4), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_slots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_slots_zone'), ['zone'], unique=False)

    op.create_table('delivery_zones',
    sa.Column('postcode', sa.String(length=8), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('zone_name', sa.String(length=80), nullable=True),
    sa.Column('base_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('install_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('postcode')
    )
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_zones_zone'), ['zone'], unique=False)

    op.create_table('slot_holds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=40), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['delivery_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_holds_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_slot_id'), ['slot_id'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_postcode', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('ship_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ship_zone', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('install_fee', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('slot_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('delivery_quoted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('delivery_quoted_at')
        batch_op.drop_column('slot_id')
        batch_op.drop_column('install_fee')
        batch_op.drop_column('shipping_fee')
        batch_op.drop_column('ship_zone')
        batch_op.drop_column('ship_address')
        batch_op.drop_column('ship_postcode')

    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_holds_slot_id'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_cart_id'))

    op.drop_table('slot_holds')
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_zones_zone'))

    op.drop_table('delivery_zones')
    with op.batch_alter_table('delivery_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_slots_zone'))
        batch_op.drop_index(batch_op.f('ix_delivery_slots_date'))

    op.drop_table('delivery_slots')
    # ### end Alembic commands ###
