"""step11 consent data requests pdpa

Revision ID: 1195f0cd4dfe
Revises: 830b3c17398a
Create Date: 2026-09-08 08:47:13.184075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1195f0cd4dfe'
down_revision: Union[str, None] = '830b3c17398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('data_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_requests_user_id'), ['user_id'], unique=False)

    # server_default: แถวเดิมที่มีอยู่แล้วต้องมีค่าเริ่มต้น ไม่งั้น NOT NULL พัง
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=16), nullable=False, server_default='service'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_marketing', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('consent_marketing_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('anonymized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('anonymized_at')
        batch_op.drop_column('consent_marketing_at')
        batch_op.drop_column('consent_marketing')

    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_data_requests_created_at'))

    op.drop_table('data_requests')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_consents_created_at'))

    op.drop_table('consents')
    # ### end Alembic commands ###
