"""step2 catalog mirror stock

Revision ID: 21177c29d17a
Revises: 3a039ae67414
Create Date: 2026-09-07 15:29:38.096295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21177c29d17a'
down_revision: Union[str, None] = '3a039ae67414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name_th', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('room', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('plant_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('zone_codes', sa.JSON(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('plant_code')
    )
    op.create_table('stock_cache',
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('plant_code', sa.String(length=8), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('atp_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('matnr', 'plant_code')
    )
    op.create_table('materials',
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('name_th', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('variant', sa.String(length=200), nullable=True),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=40), nullable=True),
    sa.Column('brand_id', sa.String(length=40), nullable=True),
    sa.Column('room', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('requires_install', sa.Boolean(), nullable=False),
    sa.Column('is_takeaway_ok', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('matnr')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_room'), ['room'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_sku'), ['sku'], unique=False)

    op.create_table('stock_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('plant_code', sa.String(length=8), nullable=False),
    sa.Column('qty_returned', sa.Integer(), nullable=False),
    sa.Column('atp_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_checks_matnr'), ['matnr'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_checks_user_id'), ['user_id'], unique=False)

    op.create_table('material_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['matnr'], ['materials.matnr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_prices_matnr'), ['matnr'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_prices_matnr'))

    op.drop_table('material_prices')
    with op.batch_alter_table('stock_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_checks_matnr'))

    op.drop_table('stock_checks')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_sku'))
        batch_op.drop_index(batch_op.f('ix_materials_room'))
        batch_op.drop_index(batch_op.f('ix_materials_category_id'))
        batch_op.drop_index(batch_op.f('ix_materials_barcode'))

    op.drop_table('materials')
    op.drop_table('stock_cache')
    op.drop_table('plants')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
