"""step9 payments sap_sync_jobs

Revision ID: 3603a90a838e
Revises: 5e1f704c3b95
Create Date: 2026-09-07 18:24:22.014490
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3603a90a838e'
down_revision: Union[str, None] = '5e1f704c3b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_no', sa.String(length=24), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=64), nullable=True),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('pay_url', sa.String(length=300), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_no')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_provider_ref'), ['provider_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('sap_sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id')
    )
    with op.batch_alter_table('sap_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sap_sync_jobs_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sap_sync_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sap_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sap_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_sap_sync_jobs_next_retry_at'))

    op.drop_table('sap_sync_jobs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_ref'))

    op.drop_table('payments')
    # ### end Alembic commands ###
