"""step8 presos quotations

Revision ID: 5e1f704c3b95
Revises: 062ca15d6b09
Create Date: 2026-09-07 18:15:31.104918
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e1f704c3b95'
down_revision: Union[str, None] = '062ca15d6b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('preso_no', sa.String(length=24), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('sales_user_id', sa.String(length=36), nullable=True),
    sa.Column('customer_user_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preso_no')
    )
    with op.batch_alter_table('presos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presos_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presos_customer_user_id'), ['customer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presos_sales_user_id'), ['sales_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presos_status'), ['status'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_no', sa.String(length=24), nullable=False),
    sa.Column('preso_id', sa.String(length=36), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('customer_user_id', sa.String(length=36), nullable=False),
    sa.Column('sales_user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('customer_snapshot', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('install_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('pdf_url', sa.String(length=300), nullable=True),
    sa.Column('ship_address', sa.Text(), nullable=True),
    sa.Column('ship_postcode', sa.String(length=8), nullable=True),
    sa.Column('ship_zone', sa.String(length=8), nullable=True),
    sa.Column('slot_id', sa.String(length=40), nullable=True),
    sa.Column('slot_date', sa.Date(), nullable=True),
    sa.Column('slot_period', sa.String(length=4), nullable=True),
    sa.Column('stock_warnings', sa.JSON(), nullable=True),
    sa.Column('sap_so_no', sa.String(length=32), nullable=True),
    sa.Column('sap_sync_status', sa.String(length=16), nullable=False),
    sa.Column('sap_sync_error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preso_id'], ['presos.id'], ),
    sa.ForeignKeyConstraint(['sales_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_no')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_customer_user_id'), ['customer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_preso_id'), ['preso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_sales_user_id'), ['sales_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_sap_so_no'), ['sap_so_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)

    op.create_table('quotation_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variant', sa.String(length=200), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supply_mode', sa.String(length=16), nullable=False),
    sa.Column('plant_code', sa.String(length=8), nullable=True),
    sa.Column('atp_date', sa.Date(), nullable=True),
    sa.Column('added_by', sa.String(length=16), nullable=False),
    sa.Column('requires_install', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_lines_quotation_id'), ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_lines_quotation_id'))

    op.drop_table('quotation_lines')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_sap_so_no'))
        batch_op.drop_index(batch_op.f('ix_quotations_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_preso_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_customer_user_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_cart_id'))

    op.drop_table('quotations')
    with op.batch_alter_table('presos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presos_status'))
        batch_op.drop_index(batch_op.f('ix_presos_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_presos_customer_user_id'))
        batch_op.drop_index(batch_op.f('ix_presos_cart_id'))

    op.drop_table('presos')
    # ### end Alembic commands ###
