"""home_media from magento cms

Revision ID: 69230fb7a824
Revises: 1195f0cd4dfe
Create Date: 2026-09-08 13:30:57.100861
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69230fb7a824'
down_revision: Union[str, None] = '1195f0cd4dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_media',
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_mb_url', sa.String(length=500), nullable=True),
    sa.Column('source_href', sa.String(length=500), nullable=True),
    sa.Column('href', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('section', 'slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_media')
    # ### end Alembic commands ###
