"""step3 carts items history audit

Revision ID: 7a033e45418a
Revises: 21177c29d17a
Create Date: 2026-09-07 15:40:27.766650
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a033e45418a'
down_revision: Union[str, None] = '21177c29d17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_sales_id', sa.String(length=36), nullable=True),
    sa.Column('anon_token', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('no', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('merged_into_cart_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['owner_sales_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carts_anon_token'), ['anon_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_customer_user_id'), ['customer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_owner_sales_id'), ['owner_sales_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_status'), ['status'], unique=False)

    op.create_table('cart_item_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('qty_before', sa.Integer(), nullable=False),
    sa.Column('qty_after', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_item_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_item_history_cart_id'), ['cart_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('variant_snapshot', sa.String(length=200), nullable=True),
    sa.Column('spec_snapshot', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('category_id', sa.String(length=40), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_tier', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.String(length=16), nullable=False),
    sa.Column('added_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('pending_ack', sa.Boolean(), nullable=False),
    sa.Column('supply_mode', sa.String(length=16), nullable=False),
    sa.Column('plant_code', sa.String(length=8), nullable=True),
    sa.Column('atp_date', sa.Date(), nullable=True),
    sa.Column('requires_install', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('cart_item_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_history_cart_id'))

    op.drop_table('cart_item_history')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_status'))
        batch_op.drop_index(batch_op.f('ix_carts_owner_sales_id'))
        batch_op.drop_index(batch_op.f('ix_carts_customer_user_id'))
        batch_op.drop_index(batch_op.f('ix_carts_anon_token'))

    op.drop_table('carts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
