"""step10 analytics order history best sellers

Revision ID: 830b3c17398a
Revises: 3603a90a838e
Create Date: 2026-09-07 18:34:47.884577
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '830b3c17398a'
down_revision: Union[str, None] = '3603a90a838e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_sellers',
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('matnr')
    )
    with op.batch_alter_table('best_sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_best_sellers_rank'), ['rank'], unique=False)

    op.create_table('material_daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('add_to_cart', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'matnr', name='uq_stat_date_matnr')
    )
    with op.batch_alter_table('material_daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_daily_stats_matnr'), ['matnr'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_daily_stats_stat_date'), ['stat_date'], unique=False)

    op.create_table('order_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('so_no', sa.String(length=32), nullable=False),
    sa.Column('sap_customer_no', sa.String(length=20), nullable=False),
    sa.Column('customer_user_id', sa.String(length=36), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('branch', sa.String(length=60), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_no')
    )
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_history_customer_user_id'), ['customer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_history_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_history_sap_customer_no'), ['sap_customer_no'], unique=False)

    op.create_table('recently_viewed',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_key', 'matnr', name='uq_recent_owner_matnr')
    )
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recently_viewed_owner_key'), ['owner_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_recently_viewed_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('anon_token', sa.String(length=64), nullable=True),
    sa.Column('q', sa.String(length=200), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('clicked_matnr', sa.String(length=18), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_q'), ['q'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_user_id'), ['user_id'], unique=False)

    op.create_table('user_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('anon_token', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=True),
    sa.Column('query', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_events_anon_token'), ['anon_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_event'), ['event'], unique=False)
        batch_op.create_index('ix_user_events_matnr_created', ['matnr', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_user_id'), ['user_id'], unique=False)

    op.create_table('wishlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matnr', name='uq_wishlist_user_matnr')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlists_user_id'), ['user_id'], unique=False)

    op.create_table('order_history_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('matnr', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_history_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_history_lines_matnr'), ['matnr'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_history_lines_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_history_lines_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_history_lines_matnr'))

    op.drop_table('order_history_lines')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_user_id'))

    op.drop_table('wishlists')
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_events_user_id'))
        batch_op.drop_index('ix_user_events_matnr_created')
        batch_op.drop_index(batch_op.f('ix_user_events_event'))
        batch_op.drop_index(batch_op.f('ix_user_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_events_anon_token'))

    op.drop_table('user_events')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_queries_q'))
        batch_op.drop_index(batch_op.f('ix_search_queries_created_at'))

    op.drop_table('search_queries')
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recently_viewed_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_recently_viewed_owner_key'))

    op.drop_table('recently_viewed')
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_history_sap_customer_no'))
        batch_op.drop_index(batch_op.f('ix_order_history_order_date'))
        batch_op.drop_index(batch_op.f('ix_order_history_customer_user_id'))

    op.drop_table('order_history')
    with op.batch_alter_table('material_daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_daily_stats_stat_date'))
        batch_op.drop_index(batch_op.f('ix_material_daily_stats_matnr'))

    op.drop_table('material_daily_stats')
    with op.batch_alter_table('best_sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_best_sellers_rank'))

    op.drop_table('best_sellers')
    # ### end Alembic commands ###
