"""step11 material created_at sold_qty

Revision ID: ad380c8e36a7
Revises: 69230fb7a824
Create Date: 2026-09-08 14:26:29.253579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad380c8e36a7'
down_revision: Union[str, None] = '69230fb7a824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        # ต้องมี server_default ไม่งั้นเติมคอลัมน์ NOT NULL ลงตารางที่มี 25,000 แถวไม่ได้
        batch_op.add_column(sa.Column('sold_qty', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_materials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_sold_qty'), ['sold_qty'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_sold_qty'))
        batch_op.drop_index(batch_op.f('ix_materials_created_at'))
        batch_op.drop_column('sold_qty')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
