"""step6 promotions applied_discounts

Revision ID: b2e3c3000095
Revises: 7a033e45418a
Create Date: 2026-09-07 16:00:40.206039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2e3c3000095'
down_revision: Union[str, None] = '7a033e45418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('applied_discounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=True),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('promo_code', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('applied_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applied_discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applied_discounts_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applied_discounts_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applied_discounts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applied_discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applied_discounts_status'))
        batch_op.drop_index(batch_op.f('ix_applied_discounts_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_applied_discounts_cart_id'))

    op.drop_table('applied_discounts')
    op.drop_table('promotions')
    # ### end Alembic commands ###
